<script setup lang="ts">
import type { ApiValidationField, Jurisdiction, QuarterInput } from '~/types/api'
import type { Recommendation } from '~/types/quarter'
const props = defineProps<{ modelValue: QuarterInput['payments']; recommendations: Record<Jurisdiction, Recommendation>; errors: ApiValidationField[] }>()
const emit = defineEmits<{ 'update:modelValue': [value: QuarterInput['payments']] }>()
function update(jurisdiction: Jurisdiction, field: 'amount_cents' | 'date', value: number | string | null) { emit('update:modelValue', { ...props.modelValue, [jurisdiction]: { ...props.modelValue[jurisdiction], [field]: value } }) }
function errorFor(jurisdiction: Jurisdiction, field: string) { return props.errors.find(error => error.path === `payments.${jurisdiction}.${field}`)?.message }
</script>
<template><UCard><template #header><h2>Estimated payments</h2><p>Record payments completed during this selected quarter.</p></template><div class="payment-grid"><section v-for="jurisdiction in ['federal', 'california'] as Jurisdiction[]" :key="jurisdiction" class="payment-card"><h3>{{ jurisdiction === 'federal' ? 'Federal' : 'California' }}</h3><MoneyInput :model-value="modelValue[jurisdiction].amount_cents" label="Amount paid" :backend-error="errorFor(jurisdiction, 'amount_cents')" @update:model-value="update(jurisdiction, 'amount_cents', $event)" /><UFormField label="Payment date"><UInput :model-value="modelValue[jurisdiction].date ?? ''" type="date" @update:model-value="update(jurisdiction, 'date', $event ? String($event) : null)" /></UFormField><p v-if="recommendations[jurisdiction].due_date" class="due-date">Due date: {{ recommendations[jurisdiction].due_date }}</p></section><UAlert v-for="error in errors" :key="error.path" class="form-wide" color="error" :description="error.message" /></div></UCard></template>
<style scoped>h2,h3,p{margin:0}p{color:var(--ui-text-muted);font-size:.875rem;margin-top:.25rem}.payment-grid{display:grid;gap:1rem;grid-template-columns:repeat(2,minmax(0,1fr))}.payment-card{border:1px solid var(--ui-border);border-radius:var(--ui-radius);display:grid;gap:1rem;padding:1rem}.form-wide{grid-column:1/-1}@media(max-width:640px){.payment-grid{grid-template-columns:1fr}}</style>
