<script setup lang="ts">
import type { ApiValidationField, ApiWarning, QuarterInput } from '~/types/api'
type Investments = NonNullable<QuarterInput['investments']>
const props = defineProps<{ modelValue: Investments | null; warnings: ApiWarning[]; errors: ApiValidationField[] }>()
const emit = defineEmits<{ 'update:modelValue': [value: Investments | null] }>()
function update<K extends keyof Investments>(field: K, value: Investments[K]) { if (props.modelValue) emit('update:modelValue', { ...props.modelValue, [field]: value }) }
function errorFor(field: string) { return props.errors.find(error => error.path === `investments.${field}`)?.message }
function createInvestments(): Investments { return { ordinary_dividends_cents: 0, qualified_dividends_cents: 0, short_term_gain_cents: 0, long_term_gain_cents: 0, federal_withholding_cents: 0, california_withholding_cents: 0, notes: null } }
</script>
<template><UCard><template #header><h2>Quarterly investments</h2><p>All values are for this selected quarter, not year to date.</p></template><div v-if="modelValue" class="form-grid"><MoneyInput :model-value="modelValue.ordinary_dividends_cents" label="Ordinary dividends" :backend-error="errorFor('ordinary_dividends_cents')" @update:model-value="update('ordinary_dividends_cents', $event as never)" /><MoneyInput :model-value="modelValue.qualified_dividends_cents" label="Qualified dividends" :backend-error="errorFor('qualified_dividends_cents')" @update:model-value="update('qualified_dividends_cents', $event as never)" /><MoneyInput :model-value="modelValue.short_term_gain_cents" allow-negative label="Net short-term gain/loss" @update:model-value="update('short_term_gain_cents', $event as never)" /><MoneyInput :model-value="modelValue.long_term_gain_cents" allow-negative label="Net long-term gain/loss" @update:model-value="update('long_term_gain_cents', $event as never)" /><MoneyInput :model-value="modelValue.federal_withholding_cents" label="Federal withholding" @update:model-value="update('federal_withholding_cents', $event as never)" /><MoneyInput :model-value="modelValue.california_withholding_cents" label="California withholding" @update:model-value="update('california_withholding_cents', $event as never)" /><UFormField class="form-wide" label="Notes (optional)"><UTextarea :model-value="modelValue.notes ?? ''" @update:model-value="update('notes', $event ? String($event) : null)" /></UFormField><WarningList :warnings="warnings" class="form-wide" /><UAlert v-for="error in errors" :key="error.path" class="form-wide" color="error" :description="error.message" /><UButton class="form-wide" color="neutral" variant="ghost" @click="emit('update:modelValue', null)">Remove investments</UButton></div><UEmpty v-else icon="i-lucide-chart-no-axes-combined" title="No investment activity entered" description="Add dividends, gains/losses, or investment withholding for this quarter."><template #actions><UButton @click="emit('update:modelValue', createInvestments())">Add investments</UButton></template></UEmpty></UCard></template>
<style scoped>h2,p{margin:0}p{color:var(--ui-text-muted);font-size:.875rem;margin-top:.25rem}.form-grid{display:grid;gap:1rem;grid-template-columns:repeat(2,minmax(0,1fr))}.form-wide{grid-column:1/-1}@media(max-width:640px){.form-grid{grid-template-columns:1fr}}</style>
