#include "estimated_taxes/recommendations.hpp"

#include <array>
#include <functional>
#include <iostream>
#include <stdexcept>

using namespace estimated_taxes;
namespace {
void require(bool value, const char* message) { if (!value) throw std::runtime_error(message); }
TaxYearInputs inputs() { TaxYearInputs value; for (int i=0;i<4;++i) value.quarters[i].quarter=i+1; return value; }
ActiveRules rules() { auto federal=official_federal_rules(); auto california=official_california_rules(); return {{1,Jurisdiction::federal,true,false,{},federal,{}},{2,Jurisdiction::california,true,false,{}, {},california},false,false}; }
TaxCalculation taxes(Cents federal, Cents california, Cents f_withholding=0, Cents c_withholding=0) { TaxCalculation result; result.federal.details.annual_liability_cents=federal; result.california.details.annual_liability_cents=california; result.federal.details.projected_withholding_cents=f_withholding; result.california.details.projected_withholding_cents=c_withholding; return result; }
void schedules_and_rounding() { auto in=inputs(); auto active=rules(); for (int quarter=1;quarter<=4;++quarter) { const std::string date=quarter==1?"2026-03-31":quarter==2?"2026-06-01":quarter==3?"2026-09-01":"2026-12-01"; const auto r=recommend_payments(in,date,taxes(101,101),active); require(*r.federal.cumulative_target_cents==multiply_rate(101,quarter*250000),"federal cumulative"); const std::array<Cents,4> ca{30,71,71,101}; require(*r.california.cumulative_target_cents==ca[quarter-1],"California cumulative"); }
 Cents total{}; Cents previous{}; for(int q=1;q<=4;++q){auto r=recommend_payments(in,q==1?"2026-03-31":q==2?"2026-06-01":q==3?"2026-09-01":"2026-12-01",taxes(101,0),active); total+=*r.federal.scheduled_installment_cents; previous=*r.federal.cumulative_target_cents;} require(total==101&&previous==101,"rounded schedule reconciles"); }
void payments_states_and_dates() { auto active=rules(); auto in=inputs(); auto r=recommend_payments(in,"2026-03-31",taxes(1000,1000),active); require(*r.federal.recommended_payment_cents==250&&*r.federal.catch_up_recommendation_cents==0&&*r.federal.scheduled_recommendation_cents==250&&*r.federal.recommendation_status==RecommendationStatus::payment_recommended,"scheduled recommendation"); require(*r.federal.due_date_status==DueDateStatus::upcoming,"upcoming"); r=recommend_payments(in,"2026-06-15",taxes(1000,0),active);require(*r.federal.due_date_status==DueDateStatus::due_today,"due today"); r=recommend_payments(in,"2026-06-16",taxes(1000,0),active);require(*r.federal.due_date_status==DueDateStatus::past_due,"past due"); in.quarters[0].federal_payment={100,"2026-04-01"}; r=recommend_payments(in,"2026-06-16",taxes(1000,0),active);require(*r.federal.recommended_payment_cents==400&&*r.federal.catch_up_recommendation_cents==150&&*r.federal.recommendation_status==RecommendationStatus::catch_up_recommended&&*r.federal.due_date_status==DueDateStatus::past_due,"catch-up past due"); }
void overpayment_and_independence() { auto active=rules(); auto in=inputs(); in.quarters[2].federal_payment={1000,"2026-03-01"}; auto r=recommend_payments(in,"2026-03-31",taxes(1000,1000,0,2000),active); require(*r.federal.payments_credited_cents==0&&*r.federal.remaining_before_recommendation_cents==0,"later payment affects annual position but not current target"); require(r.california.projected_overpayment&&*r.california.recommendation_status==RecommendationStatus::no_payment_currently_needed,"withholding overpayment"); in.quarters[0].federal_payment={2000,"2026-03-01"}; r=recommend_payments(in,"2026-03-31",taxes(1000,1000),active);require(r.federal.projected_overpayment&&*r.federal.recommended_payment_cents==0,"payment overpayment"); }
void insufficient_and_invalid_payment() { auto in=inputs(); auto active=rules(); std::vector<ValidationOutcome> validation{{ValidationSeverity::blocking,Jurisdiction::federal,"bad","bad"}}; auto r=recommend_payments(in,"2026-03-31",taxes(1000,0),active,validation); require(r.federal.calculation_status==CalculationStatus::insufficient_information&&!r.federal.recommendation_status&&!r.federal.recommended_payment_cents&&r.federal.due_date_status,"blocking suppresses amount"); require(r.california.calculation_status==CalculationStatus::available,"independent blocking"); in.quarters[0].federal_payment={1,"2026-04-02"}; bool rejected{};try{(void)recommend_payments(in,"2026-03-31",taxes(0,0),active);}catch(const RecommendationError&){rejected=true;}require(rejected,"future payment rejected"); }
void targets_outlook_and_california_q3(){ auto active=rules(); auto in=inputs();
  auto r=recommend_payments(in,"2026-03-31",taxes(1000,1000,1000,1000),active); require(*r.federal.annual_target_cents==0&&*r.california.recommended_payment_cents==0,"zero annual target");
  r=recommend_payments(in,"2026-03-31",taxes(1000,0,999,0),active); require(*r.federal.annual_target_cents==1,"liability above withholding");
  r=recommend_payments(in,"2026-03-31",taxes(1000,0,1001,0),active); require(r.federal.projected_overpayment&&*r.federal.recommended_payment_cents==0,"liability below withholding");
  r=recommend_payments(in,"2026-03-31",taxes(1000,0),active); require(*r.federal.remaining_before_recommendation_cents==1000&&*r.federal.remaining_after_recommendation_cents==750,"remaining amounts reconcile"); require(r.federal.future_outlook.size()==3&&r.federal.future_outlook[0].cumulative_target_cents==500&&r.federal.future_outlook[0].recommended_payment_cents==250,"future outlook assumes current payment");
  in.quarters[0].federal_payment={250,"2026-03-31"}; r=recommend_payments(in,"2026-03-31",taxes(1000,0),active); require(*r.federal.payments_credited_cents==250&&*r.federal.recommended_payment_cents==0,"payment on as-of date is credited");
  in.quarters[0].california_payment={700,"2026-03-31"}; r=recommend_payments(in,"2026-09-10",taxes(0,1000),active); require(*r.california.scheduled_installment_cents==0&&*r.california.recommended_payment_cents==0,"California Q3 zero scheduled no catch-up");
  in.quarters[0].california_payment={600,"2026-03-31"}; r=recommend_payments(in,"2026-09-10",taxes(0,1000),active); require(*r.california.scheduled_installment_cents==0&&*r.california.catch_up_recommendation_cents==100&&*r.california.recommendation_status==RecommendationStatus::catch_up_recommended,"California Q3 catch-up");
}
void payment_boundaries_and_validation(){ auto active=rules(); auto in=inputs();
  in.quarters[0].federal_payment={500,"2026-03-31"}; auto r=recommend_payments(in,"2026-06-01",taxes(1000,0),active); require(*r.federal.recommended_payment_cents==0,"exact cumulative target payment");
  in.quarters[0].federal_payment={600,"2026-03-31"}; r=recommend_payments(in,"2026-06-01",taxes(1000,0),active); require(*r.federal.recommended_payment_cents==0,"excess cumulative payment");
  in.quarters[0].federal_payment={2000,"2026-03-31"}; r=recommend_payments(in,"2026-06-01",taxes(1000,0),active); require(r.federal.projected_overpayment_cents==1000,"payments exceeding annual target");
  in.quarters[0].federal_payment={500,"2026-03-31"}; r=recommend_payments(in,"2026-06-01",taxes(200,0),active); require(*r.federal.recommended_payment_cents==0,"falling projection can eliminate payment");
  const std::vector<ValidationOutcome> notices{{ValidationSeverity::caution,Jurisdiction::federal,"caution","caution"},{ValidationSeverity::informational,std::nullopt,"information","information"}}; r=recommend_payments(inputs(),"2026-03-31",taxes(1000,0),active,notices); require(r.validation.size()==2&&r.federal.calculation_status==CalculationStatus::available,"caution and informational validation remain distinguishable");
}
void composition(){ auto active=rules(); auto in=inputs(); Household household; const auto result=compose_current_result(household,in,"2026-03-31",active); require(result.as_of_date=="2026-03-31"&&result.recommendations.federal.rule_revision_id==active.federal.id&&result.recommendations.california.rule_revision_id==active.california.id,"composed result retains all stages"); }
}
int main(){const std::array tests{std::pair{"schedules",schedules_and_rounding},std::pair{"states",payments_states_and_dates},std::pair{"overpayment",overpayment_and_independence},std::pair{"validation",insufficient_and_invalid_payment},std::pair{"targets and outlook",targets_outlook_and_california_q3},std::pair{"payment boundaries",payment_boundaries_and_validation},std::pair{"composition",composition}};int failures{};for(auto [n,t]:tests)try{t();std::cout<<"PASS: "<<n<<'\n';}catch(const std::exception&e){++failures;std::cerr<<"FAIL: "<<n<<": "<<e.what()<<'\n';}return failures;}
