#include "estimated_taxes/tax_rules.hpp"
#include <sqlite3.h>
#include <filesystem>
#include <functional>
#include <iostream>
#include <stdexcept>
using namespace estimated_taxes; namespace fs=std::filesystem;
namespace {
class Temp { public: Temp(){static int n{};p=(fs::temp_directory_path()/("estimated-rules-"+std::to_string(++n)+".db")).string();fs::remove(p);}~Temp(){fs::remove(p);}std::string p;};
void need(bool x,const char* m){if(!x)throw std::runtime_error(m);}template<class E,class F>void throws(F f,const char*m){try{f();}catch(const E&){return;}throw std::runtime_error(m);}
void test_defaults_and_validation(){auto f=official_federal_rules();auto c=official_california_rules();validate(f);validate(c);need(f.standard_deduction_cents==3220000&&f.age_or_blind_addition_cents==165000,"federal defaults");need(c.joint_personal_exemption_credit_cents==30600&&c.capital_loss_limit_cents==300000,"California exact cents");auto bad=f;bad.tax_year=2025;throws<RuleValidationError>([&]{validate(bad);},"year");bad=f;bad.niit_rate_ppm=1000001;throws<RuleValidationError>([&]{validate(bad);},"rate");bad=f;bad.ordinary_brackets[1].lower_bound_cents++;throws<RuleValidationError>([&]{validate(bad);},"gap");bad=f;bad.ordinary_brackets[0].upper_bound_cents=0;throws<RuleValidationError>([&]{validate(bad);},"reversed");bad=f;bad.ordinary_brackets.back().upper_bound_cents=999;throws<RuleValidationError>([&]{validate(bad);},"closed final");bad=f;bad.installments.pop_back();throws<RuleValidationError>([&]{validate(bad);},"installment count");bad=f;bad.installments[1].due_date="2026-01-01";throws<RuleValidationError>([&]{validate(bad);},"date order");bad=f;bad.installments[1].period_ppm++;throws<RuleValidationError>([&]{validate(bad);},"period percentage");auto cbad=c;cbad.standard_deduction_cents=-1;throws<RuleValidationError>([&]{validate(cbad);},"negative");}
void test_seed_migration_and_roundtrip(){Temp t;InputStore b1(t.p);need(b1.schema_version()==1,"B1 database");RuleStore s(t.p);need(InputStore(t.p).schema_version()==2,"migrated");auto a=s.load_active();need(a.federal.official_baseline&&a.california.official_baseline&&!a.federal_customized&&!a.california_customized,"official active");need(a.california.california->joint_personal_exemption_credit_cents==30600&&a.california.california->capital_loss_limit_cents==300000,"stored cents");need(a.california.sources.size()==4,"provenance retained");RuleStore reopen(t.p);auto r=reopen.load_active();need(r.federal.id==a.federal.id&&r.california.id==a.california.id,"no duplicate seed");}
void test_official_baselines_are_immutable(){Temp t;RuleStore s(t.p);auto active=s.load_active();sqlite3* db{};need(sqlite3_open(t.p.c_str(),&db)==SQLITE_OK,"open");const auto id=active.federal.id;std::string update="UPDATE rule_revisions SET payload='bad' WHERE id="+std::to_string(id);std::string remove="DELETE FROM rule_revisions WHERE id="+std::to_string(id);need(sqlite3_exec(db,update.c_str(),nullptr,nullptr,nullptr)==SQLITE_CONSTRAINT,"baseline update denied");need(sqlite3_exec(db,remove.c_str(),nullptr,nullptr,nullptr)==SQLITE_CONSTRAINT,"baseline delete denied");sqlite3_close(db);need(s.load_active().federal.federal==official_federal_rules(),"baseline values unchanged");}
void test_replace_archive_restore_and_customization(){Temp t;RuleStore s(t.p);auto initial=s.load_active();auto f=official_federal_rules();auto c=official_california_rules();f.standard_deduction_cents++;s.replace_active(f,c);auto changed=s.load_active();need(changed.federal.id!=initial.federal.id&&changed.california.id!=initial.california.id&&changed.federal_customized&&!changed.california_customized,"atomic active replacement");auto archive=s.archived_revisions(Jurisdiction::federal);need(archive.empty(),"immutable baseline is not an archived revision");}
void test_restore_and_rollback(){Temp t;RuleStore s(t.p);auto f=official_federal_rules();auto c=official_california_rules();f.standard_deduction_cents+=100;s.replace_active(f,c);auto custom=s.load_active();auto archived=s.archived_revisions(Jurisdiction::federal);need(archived.empty(),"only baseline exists before another revision");s.restore_official(Jurisdiction::federal);auto restored=s.load_active();need(restored.federal.id!=custom.federal.id&&!restored.federal_customized&&restored.federal.federal==official_federal_rules(),"official restore copies");auto list=s.archived_revisions(Jurisdiction::federal);need(list.size()==1&&list[0].id==custom.federal.id,"custom archived");s.restore_archived(Jurisdiction::federal,custom.federal.id);auto copied=s.load_active();need(copied.federal.id!=custom.federal.id&&copied.federal.federal==custom.federal.federal&&copied.federal_customized,"archive restore copies");auto before=s.load_active();auto bad=official_california_rules();bad.standard_deduction_cents=-1;throws<RuleValidationError>([&]{s.replace_active(official_federal_rules(),bad);},"invalid replacement");need(s.load_active().federal.id==before.federal.id&&s.load_active().california.id==before.california.id,"invalid rollback");sqlite3*db{};need(sqlite3_open(t.p.c_str(),&db)==SQLITE_OK,"open");need(sqlite3_exec(db,"CREATE TRIGGER fail_ca BEFORE INSERT ON rule_revisions WHEN NEW.jurisdiction='california' BEGIN SELECT RAISE(ABORT,'fail'); END;",nullptr,nullptr,nullptr)==SQLITE_OK,"trigger");sqlite3_close(db);throws<StorageError>([&]{s.replace_active(official_federal_rules(),official_california_rules());},"db failure");need(s.load_active().federal.id==before.federal.id,"storage rollback");}
}
int main(){std::pair<const char*,std::function<void()>> ts[]={{"defaults and validation",test_defaults_and_validation},{"seed migration and roundtrip",test_seed_migration_and_roundtrip},{"official baseline immutability",test_official_baselines_are_immutable},{"replacement and customization",test_replace_archive_restore_and_customization},{"restore and rollback",test_restore_and_rollback}};int fail{};for(auto&[n,t]:ts)try{t();std::cout<<"PASS: "<<n<<'\n';}catch(const std::exception&e){++fail;std::cerr<<"FAIL: "<<n<<": "<<e.what()<<'\n';}return fail;}
