#include "estimated_taxes/snapshot_store.hpp"
#include "estimated_taxes/sqlite.hpp"
#include "estimated_taxes/tax_rules.hpp"

#include <sqlite3.h>

#include <iomanip>
#include <sstream>

namespace estimated_taxes {
namespace {
class Writer { public: template<class T> void pod(T v){ out_<<static_cast<std::int64_t>(v)<<' '; } void text(const std::string& v){out_<<std::quoted(v)<<' ';} std::string str()const{return out_.str();} private:std::ostringstream out_; };
class Reader { public: explicit Reader(const std::string& v):in_(v){} template<class T> T pod(){std::int64_t v{};if(!(in_>>v))throw StorageError("invalid snapshot payload");return static_cast<T>(v);} std::string text(){std::string v;if(!(in_>>std::quoted(v)))throw StorageError("invalid snapshot payload");return v;} void done(){std::string x;if(in_>>x)throw StorageError("invalid snapshot payload");} private:std::istringstream in_; };
template<class F> void optional(Writer&w,const std::optional<F>&v,void(*put)(Writer&,const F&)){w.pod(v.has_value());if(v)put(w,*v);}template<class F> std::optional<F> optional(Reader&r,F(*get)(Reader&)){if(!r.pod<bool>())return{};return get(r);}template<class F> void vector(Writer&w,const std::vector<F>&v,void(*put)(Writer&,const F&)){w.pod(v.size());for(auto&x:v)put(w,x);}template<class F> std::vector<F> vector(Reader&r,F(*get)(Reader&)){std::vector<F>v;for(auto n=r.pod<size_t>();n--;){v.push_back(get(r));}return v;}
void spouse(Writer&w,const Spouse&v){w.pod(v.key);w.text(v.label);w.pod(v.age_65_or_older);w.pod(v.blind);} Spouse spouse(Reader&r){return {r.pod<SpouseKey>(),r.text(),r.pod<bool>(),r.pod<bool>()};}
void paystub(Writer&w,const PaystubSnapshot&v){w.text(v.date);w.text(v.pay_frequency);for(auto x:{v.current_period_regular_wages_cents,v.current_period_bonus_wages_cents,v.current_period_federal_withholding_cents,v.current_period_california_withholding_cents,v.federal_taxable_wages_ytd_cents,v.california_taxable_wages_ytd_cents,v.federal_withholding_ytd_cents,v.california_withholding_ytd_cents,v.social_security_withholding_ytd_cents,v.medicare_withholding_ytd_cents,v.california_sdi_withholding_ytd_cents})w.pod(x);} PaystubSnapshot paystub(Reader&r){PaystubSnapshot v{r.text(),r.text()};Cents* x[]={&v.current_period_regular_wages_cents,&v.current_period_bonus_wages_cents,&v.current_period_federal_withholding_cents,&v.current_period_california_withholding_cents,&v.federal_taxable_wages_ytd_cents,&v.california_taxable_wages_ytd_cents,&v.federal_withholding_ytd_cents,&v.california_withholding_ytd_cents,&v.social_security_withholding_ytd_cents,&v.medicare_withholding_ytd_cents,&v.california_sdi_withholding_ytd_cents};for(auto p:x)*p=r.pod<Cents>();return v;}
void investment(Writer&w,const InvestmentSummary&v){for(auto x:{v.ordinary_dividends_cents,v.qualified_dividends_cents,v.short_term_gain_cents,v.long_term_gain_cents,v.federal_withholding_cents,v.california_withholding_cents})w.pod(x);optional<std::string>(w,v.notes,[](Writer&a,const std::string&b){a.text(b);});} InvestmentSummary investment(Reader&r){InvestmentSummary v;Cents*x[]={&v.ordinary_dividends_cents,&v.qualified_dividends_cents,&v.short_term_gain_cents,&v.long_term_gain_cents,&v.federal_withholding_cents,&v.california_withholding_cents};for(auto p:x)*p=r.pod<Cents>();v.notes=optional<std::string>(r,[](Reader&a){return a.text();});return v;}
void payment(Writer&w,const EstimatedPayment&v){w.pod(v.amount_cents);optional<std::string>(w,v.date,[](Writer&a,const std::string&b){a.text(b);});} EstimatedPayment payment(Reader&r){EstimatedPayment v;v.amount_cents=r.pod<Cents>();v.date=optional<std::string>(r,[](Reader&a){return a.text();});return v;}
void quarter(Writer&w,const QuarterInput&v){w.pod(v.quarter);optional<PaystubSnapshot>(w,v.spouse_1_paystub,paystub);optional<PaystubSnapshot>(w,v.spouse_2_paystub,paystub);optional<InvestmentSummary>(w,v.investments,investment);payment(w,v.federal_payment);payment(w,v.california_payment);} QuarterInput quarter(Reader&r){QuarterInput v;v.quarter=r.pod<int>();v.spouse_1_paystub=optional<PaystubSnapshot>(r,paystub);v.spouse_2_paystub=optional<PaystubSnapshot>(r,paystub);v.investments=optional<InvestmentSummary>(r,investment);v.federal_payment=payment(r);v.california_payment=payment(r);return v;}
void bracket(Writer&w,const Bracket&v){w.pod(v.lower_bound_cents);optional<Cents>(w,v.upper_bound_cents,[](Writer&a,const Cents&b){a.pod(b);});w.pod(v.rate_ppm);} Bracket bracket(Reader&r){Bracket v;v.lower_bound_cents=r.pod<Cents>();v.upper_bound_cents=optional<Cents>(r,[](Reader&a){return a.pod<Cents>();});v.rate_ppm=r.pod<int>();return v;}
void installment(Writer&w,const Installment&v){w.pod(v.quarter);w.text(v.due_date);w.pod(v.period_ppm);w.pod(v.cumulative_ppm);} Installment installment(Reader&r){return {r.pod<int>(),r.text(),r.pod<int>(),r.pod<int>()};}
void source(Writer&w,const Source&v){for(auto x:{&v.agency,&v.title,&v.url,&v.publication_date,&v.verification_date,&v.interpretation_note})w.text(*x);} Source source(Reader&r){return {r.text(),r.text(),r.text(),r.text(),r.text(),r.text()};}
void amounts(Writer&w,const ProjectionAmounts&v){w.pod(v.actual_cents);w.pod(v.projected_remaining_cents);w.pod(v.projected_annual_cents);} ProjectionAmounts amounts(Reader&r){return {r.pod<Cents>(),r.pod<Cents>(),r.pod<Cents>()};}
void warning(Writer&w,const ProjectionWarning&v){w.pod(v.severity);w.text(v.code);w.text(v.path);w.text(v.message);} ProjectionWarning warning(Reader&r){return {r.pod<WarningSeverity>(),r.text(),r.text(),r.text()};}
void projection(Writer&w,const AnnualProjection&v){for(auto&s:v.spouses){w.pod(s.spouse);optional<int>(w,s.authoritative_quarter,[](Writer&a,const int&b){a.pod(b);});w.pod(s.remaining_pay_periods);amounts(w,s.federal_wages);amounts(w,s.california_wages);amounts(w,s.federal_withholding);amounts(w,s.california_withholding);}amounts(w,v.federal_wages);amounts(w,v.california_wages);amounts(w,v.federal_withholding);amounts(w,v.california_withholding);for(auto x:{v.investments.ordinary_dividends_cents,v.investments.qualified_dividends_cents,v.investments.short_term_gain_cents,v.investments.long_term_gain_cents,v.investments.federal_withholding_cents,v.investments.california_withholding_cents})w.pod(x);vector<ProjectionWarning>(w,v.warnings,warning);} AnnualProjection projection(Reader&r){AnnualProjection v;for(auto&s:v.spouses){s.spouse=r.pod<SpouseKey>();s.authoritative_quarter=optional<int>(r,[](Reader&a){return a.pod<int>();});s.remaining_pay_periods=r.pod<int>();s.federal_wages=amounts(r);s.california_wages=amounts(r);s.federal_withholding=amounts(r);s.california_withholding=amounts(r);}v.federal_wages=amounts(r);v.california_wages=amounts(r);v.federal_withholding=amounts(r);v.california_withholding=amounts(r);Cents*x[]={&v.investments.ordinary_dividends_cents,&v.investments.qualified_dividends_cents,&v.investments.short_term_gain_cents,&v.investments.long_term_gain_cents,&v.investments.federal_withholding_cents,&v.investments.california_withholding_cents};for(auto p:x)*p=r.pod<Cents>();v.warnings=vector<ProjectionWarning>(r,warning);return v;}
void federal_rules(Writer&w,const FederalRules&v){w.pod(v.tax_year);for(auto x:{v.standard_deduction_cents,v.age_or_blind_addition_cents,v.capital_loss_limit_cents,v.niit_threshold_cents})w.pod(x);w.pod(v.niit_rate_ppm);w.pod(v.additional_medicare_threshold_cents);w.pod(v.additional_medicare_rate_ppm);vector<Bracket>(w,v.ordinary_brackets,bracket);vector<Bracket>(w,v.preferential_brackets,bracket);vector<Installment>(w,v.installments,installment);} FederalRules federal_rules(Reader&r){FederalRules v;v.tax_year=r.pod<int>();v.standard_deduction_cents=r.pod<Cents>();v.age_or_blind_addition_cents=r.pod<Cents>();v.capital_loss_limit_cents=r.pod<Cents>();v.niit_threshold_cents=r.pod<Cents>();v.niit_rate_ppm=r.pod<int>();v.additional_medicare_threshold_cents=r.pod<Cents>();v.additional_medicare_rate_ppm=r.pod<int>();v.ordinary_brackets=vector<Bracket>(r,bracket);v.preferential_brackets=vector<Bracket>(r,bracket);v.installments=vector<Installment>(r,installment);return v;}
void california_rules(Writer&w,const CaliforniaRules&v){w.pod(v.tax_year);for(auto x:{v.standard_deduction_cents,v.joint_personal_exemption_credit_cents,v.capital_loss_limit_cents,v.behavioral_health_services_threshold_cents})w.pod(x);w.pod(v.behavioral_health_services_rate_ppm);vector<Bracket>(w,v.ordinary_brackets,bracket);vector<Installment>(w,v.installments,installment);} CaliforniaRules california_rules(Reader&r){CaliforniaRules v;v.tax_year=r.pod<int>();v.standard_deduction_cents=r.pod<Cents>();v.joint_personal_exemption_credit_cents=r.pod<Cents>();v.capital_loss_limit_cents=r.pod<Cents>();v.behavioral_health_services_threshold_cents=r.pod<Cents>();v.behavioral_health_services_rate_ppm=r.pod<int>();v.ordinary_brackets=vector<Bracket>(r,bracket);v.installments=vector<Installment>(r,installment);return v;}
void revision(Writer&w,const RuleRevision&v){w.pod(v.id);w.pod(v.jurisdiction);w.pod(v.official_baseline);w.pod(v.modified);vector<Source>(w,v.sources,source);optional<FederalRules>(w,v.federal,federal_rules);optional<CaliforniaRules>(w,v.california,california_rules);} RuleRevision revision(Reader&r){RuleRevision v;v.id=r.pod<std::int64_t>();v.jurisdiction=r.pod<Jurisdiction>();v.official_baseline=r.pod<bool>();v.modified=r.pod<bool>();v.sources=vector<Source>(r,source);v.federal=optional<FederalRules>(r,federal_rules);v.california=optional<CaliforniaRules>(r,california_rules);return v;}
void tax_details(Writer&w,const TaxCalculationDetails&v){for(auto x:{v.supported_agi_cents,v.deduction_cents,v.taxable_income_cents,v.preferential_pool_cents,v.ordinary_taxable_income_cents,v.ordinary_tax_cents,v.preferential_tax_cents,v.ordinary_tax_on_all_income_cents,v.regular_tax_cents,v.exemption_credit_cents,v.tax_before_exemption_cents,v.tax_after_exemption_cents,v.niit_cents,v.additional_medicare_cents,v.behavioral_health_services_cents,v.annual_liability_cents,v.projected_withholding_cents,v.amount_requiring_estimated_payments_cents})w.pod(x);} TaxCalculationDetails tax_details(Reader&r){TaxCalculationDetails v;Cents*x[]={&v.supported_agi_cents,&v.deduction_cents,&v.taxable_income_cents,&v.preferential_pool_cents,&v.ordinary_taxable_income_cents,&v.ordinary_tax_cents,&v.preferential_tax_cents,&v.ordinary_tax_on_all_income_cents,&v.regular_tax_cents,&v.exemption_credit_cents,&v.tax_before_exemption_cents,&v.tax_after_exemption_cents,&v.niit_cents,&v.additional_medicare_cents,&v.behavioral_health_services_cents,&v.annual_liability_cents,&v.projected_withholding_cents,&v.amount_requiring_estimated_payments_cents};for(auto p:x)*p=r.pod<Cents>();return v;}
void tax_result(Writer&w,const TaxResult&v){tax_details(w,v.details);for(auto x:{v.capital_netting.ordinary_gain_cents,v.capital_netting.preferential_gain_cents,v.capital_netting.deductible_loss_cents,v.capital_netting.unused_loss_cents})w.pod(x);w.pod(v.effective_rate_ppm);w.pod(v.rule_revision_id);vector<ProjectionWarning>(w,v.warnings,warning);} TaxResult tax_result(Reader&r){TaxResult v;v.details=tax_details(r);Cents*x[]={&v.capital_netting.ordinary_gain_cents,&v.capital_netting.preferential_gain_cents,&v.capital_netting.deductible_loss_cents,&v.capital_netting.unused_loss_cents};for(auto p:x)*p=r.pod<Cents>();v.effective_rate_ppm=r.pod<int>();v.rule_revision_id=r.pod<std::int64_t>();v.warnings=vector<ProjectionWarning>(r,warning);return v;}
void outcome(Writer&w,const ValidationOutcome&v){w.pod(v.severity);optional<Jurisdiction>(w,v.jurisdiction,[](Writer&a,const Jurisdiction&b){a.pod(b);});w.text(v.code);w.text(v.message);} ValidationOutcome outcome(Reader&r){ValidationOutcome v;v.severity=r.pod<ValidationSeverity>();v.jurisdiction=optional<Jurisdiction>(r,[](Reader&a){return a.pod<Jurisdiction>();});v.code=r.text();v.message=r.text();return v;}
void recommendation(Writer&w,const PaymentRecommendation&v){w.pod(v.calculation_status);optional<RecommendationStatus>(w,v.recommendation_status,[](Writer&a,const RecommendationStatus&b){a.pod(b);});optional<DueDateStatus>(w,v.due_date_status,[](Writer&a,const DueDateStatus&b){a.pod(b);});w.pod(v.projected_overpayment_cents);w.pod(v.projected_overpayment);for(auto x:{&v.annual_target_cents,&v.cumulative_target_cents,&v.payments_credited_cents,&v.scheduled_installment_cents,&v.scheduled_recommendation_cents,&v.catch_up_recommendation_cents,&v.recommended_payment_cents,&v.remaining_before_recommendation_cents,&v.remaining_after_recommendation_cents})optional<Cents>(w,*x,[](Writer&a,const Cents&b){a.pod(b);});w.pod(v.current_quarter);optional<std::string>(w,v.due_date,[](Writer&a,const std::string&b){a.text(b);});w.pod(v.future_outlook.size());for(auto&x:v.future_outlook){w.pod(x.quarter);w.pod(x.cumulative_target_cents);w.pod(x.recommended_payment_cents);}w.pod(v.rule_revision_id);} PaymentRecommendation recommendation(Reader&r){PaymentRecommendation v;v.calculation_status=r.pod<CalculationStatus>();v.recommendation_status=optional<RecommendationStatus>(r,[](Reader&a){return a.pod<RecommendationStatus>();});v.due_date_status=optional<DueDateStatus>(r,[](Reader&a){return a.pod<DueDateStatus>();});v.projected_overpayment_cents=r.pod<Cents>();v.projected_overpayment=r.pod<bool>();std::optional<Cents>*x[]={&v.annual_target_cents,&v.cumulative_target_cents,&v.payments_credited_cents,&v.scheduled_installment_cents,&v.scheduled_recommendation_cents,&v.catch_up_recommendation_cents,&v.recommended_payment_cents,&v.remaining_before_recommendation_cents,&v.remaining_after_recommendation_cents};for(auto p:x)*p=optional<Cents>(r,[](Reader&a){return a.pod<Cents>();});v.current_quarter=r.pod<int>();v.due_date=optional<std::string>(r,[](Reader&a){return a.text();});for(auto n=r.pod<size_t>();n--;) {v.future_outlook.push_back({r.pod<int>(),r.pod<Cents>(),r.pod<Cents>()});}v.rule_revision_id=r.pod<std::int64_t>();return v;}
std::string encode(const CalculationSnapshot&v){Writer w;w.text(v.as_of_date);spouse(w,v.household.spouse_1);spouse(w,v.household.spouse_2);for(auto&q:v.inputs.quarters)quarter(w,q);projection(w,v.projection);revision(w,v.rules.federal);revision(w,v.rules.california);w.pod(v.rules.federal_customized);w.pod(v.rules.california_customized);tax_result(w,v.taxes.federal);tax_result(w,v.taxes.california);recommendation(w,v.recommendations.federal);recommendation(w,v.recommendations.california);vector<ValidationOutcome>(w,v.recommendations.validation,outcome);return w.str();}
CalculationSnapshot decode(const std::string&s){Reader r(s);CalculationSnapshot v;v.as_of_date=r.text();v.household.spouse_1=spouse(r);v.household.spouse_2=spouse(r);for(auto&q:v.inputs.quarters)q=quarter(r);v.projection=projection(r);v.rules.federal=revision(r);v.rules.california=revision(r);v.rules.federal_customized=r.pod<bool>();v.rules.california_customized=r.pod<bool>();v.taxes.federal=tax_result(r);v.taxes.california=tax_result(r);v.recommendations.federal=recommendation(r);v.recommendations.california=recommendation(r);v.recommendations.validation=vector<ValidationOutcome>(r,outcome);r.done();return v;}
}
struct SnapshotStore::Connection { explicit Connection(const std::string&p):sqlite(p){} sqlite::Connection sqlite; };
SnapshotStore::SnapshotStore(const std::string&path):connection_(std::make_unique<Connection>(path)){InputStore inputs(path); RuleStore rules(path); sqlite::Transaction tx(connection_->sqlite);connection_->sqlite.execute("CREATE TABLE IF NOT EXISTS calculation_snapshots (id INTEGER PRIMARY KEY, name TEXT NOT NULL CHECK(length(name)>0), as_of_date TEXT NOT NULL, payload TEXT NOT NULL)");sqlite::Statement migration(connection_->sqlite.get(),"INSERT OR IGNORE INTO schema_migrations(version) VALUES(3)");migration.step_done("record snapshot migration");tx.commit();}
SnapshotStore::~SnapshotStore()=default;
CalculationSnapshot SnapshotStore::save(CalculationSnapshot value){if(value.name.empty())throw ValidationError("snapshot name cannot be empty");if(!value.rules.federal.federal||!value.rules.california.california)throw ValidationError("snapshot rules are incomplete");validate(value.household);for(auto&q:value.inputs.quarters)validate(q);validate(*value.rules.federal.federal);validate(*value.rules.california.california);value.projection=project_annual(value.inputs,value.as_of_date);value.taxes=calculate_tax(value.projection,value.household,value.rules);value.recommendations=recommend_payments(value.inputs,value.as_of_date,value.taxes,value.rules,std::move(value.recommendations.validation));const std::string payload=encode(value);sqlite::Transaction tx(connection_->sqlite);sqlite::Statement s(connection_->sqlite.get(),"INSERT INTO calculation_snapshots(name,as_of_date,payload) VALUES(?,?,?)");s.bind_text(1,value.name);s.bind_text(2,value.as_of_date);s.bind_text(3,payload);s.step_done("save snapshot");value.id=sqlite3_last_insert_rowid(connection_->sqlite.get());tx.commit();return value;}
CalculationSnapshot SnapshotStore::load(std::int64_t id)const{sqlite::Statement s(connection_->sqlite.get(),"SELECT name,as_of_date,payload FROM calculation_snapshots WHERE id=?");s.bind_integer(1,id);if(!s.step_row())throw StorageError("snapshot not found");auto v=decode(s.required_text(2,"snapshot payload"));v.id=id;v.name=s.required_text(0,"snapshot name");if(v.as_of_date!=s.required_text(1,"snapshot as-of date"))throw StorageError("snapshot as-of date is inconsistent");return v;}
std::vector<CalculationSnapshot> SnapshotStore::list()const{sqlite::Statement s(connection_->sqlite.get(),"SELECT id FROM calculation_snapshots ORDER BY id");std::vector<CalculationSnapshot>v;while(s.step_row())v.push_back(load(s.integer(0)));return v;}
void SnapshotStore::rename(std::int64_t id,const std::string&name){if(name.empty())throw ValidationError("snapshot name cannot be empty");sqlite::Statement s(connection_->sqlite.get(),"UPDATE calculation_snapshots SET name=? WHERE id=?");s.bind_text(1,name);s.bind_integer(2,id);s.step_done("rename snapshot");if(sqlite3_changes(connection_->sqlite.get())!=1)throw StorageError("snapshot not found");}
void SnapshotStore::remove(std::int64_t id){sqlite::Statement s(connection_->sqlite.get(),"DELETE FROM calculation_snapshots WHERE id=?");s.bind_integer(1,id);s.step_done("delete snapshot");if(sqlite3_changes(connection_->sqlite.get())!=1)throw StorageError("snapshot not found");}
} // namespace estimated_taxes
