#include "estimated_taxes/tax_rules.hpp"
#include "estimated_taxes/sqlite.hpp"

#include <sqlite3.h>

#include <charconv>
#include <chrono>
#include <memory>
#include <sstream>

namespace estimated_taxes {
namespace {
constexpr int kRuleSchemaVersion = 3;

const char* jurisdiction_name(Jurisdiction value) { return value == Jurisdiction::federal ? "federal" : "california"; }
Jurisdiction jurisdiction_from(const std::string& value) {
  if (value == "federal") return Jurisdiction::federal;
  if (value == "california") return Jurisdiction::california;
  throw StorageError("stored jurisdiction is invalid");
}
bool valid_date(const std::string& value) {
  if (value.size() != 10 || value[4] != '-' || value[7] != '-') return false;
  for (const int index : {0,1,2,3,5,6,8,9}) if (value[index] < '0' || value[index] > '9') return false;
  const int year = std::stoi(value.substr(0, 4)); const unsigned month = std::stoi(value.substr(5, 2)); const unsigned day = std::stoi(value.substr(8, 2));
  return year >= 2026 && year <= 2027 && std::chrono::year_month_day{std::chrono::year{year},std::chrono::month{month},std::chrono::day{day}}.ok();
}
void validate_brackets(const std::vector<Bracket>& brackets) {
  if (brackets.empty() || brackets.front().lower_bound_cents != 0) throw RuleValidationError("brackets must begin at zero");
  for (size_t i = 0; i < brackets.size(); ++i) { const auto& bracket = brackets[i];
    if (bracket.lower_bound_cents < 0 || bracket.rate_ppm < 0 || bracket.rate_ppm > 1'000'000) throw RuleValidationError("invalid bracket value");
    if (i + 1 == brackets.size()) { if (bracket.upper_bound_cents) throw RuleValidationError("final bracket must be open-ended"); }
    else if (!bracket.upper_bound_cents || *bracket.upper_bound_cents <= bracket.lower_bound_cents || *bracket.upper_bound_cents != brackets[i+1].lower_bound_cents) throw RuleValidationError("brackets must be contiguous");
  }
}
void validate_installments(const std::vector<Installment>& installments) {
  if (installments.size() != 4) throw RuleValidationError("exactly four installments are required");
  int prior{}; std::string date;
  for (size_t i = 0; i < installments.size(); ++i) { const auto& item = installments[i];
    if (item.quarter != static_cast<int>(i + 1) || !valid_date(item.due_date) || (!date.empty() && item.due_date <= date) || item.period_ppm < 0 || item.period_ppm > 1'000'000 || item.cumulative_ppm < prior || item.cumulative_ppm > 1'000'000 || item.period_ppm != item.cumulative_ppm-prior) throw RuleValidationError("invalid installments");
    date = item.due_date; prior = item.cumulative_ppm;
  }
  if (prior != 1'000'000) throw RuleValidationError("installments must total 100 percent");
}
void nonnegative(Cents value) { if (value < 0) throw RuleValidationError("rule amount cannot be negative"); }
std::vector<std::string> split(const std::string& text, char separator) { std::vector<std::string> values; std::stringstream stream(text); std::string value; while (std::getline(stream, value, separator)) if (!value.empty()) values.push_back(value); return values; }
std::int64_t number(const std::string& text) { std::int64_t value{}; const auto [end,error] = std::from_chars(text.data(), text.data()+text.size(), value); if (error != std::errc{} || end != text.data()+text.size()) throw StorageError("invalid stored rule payload"); return value; }
int integer(const std::string& text) { const auto value = number(text); if (value < std::numeric_limits<int>::min() || value > std::numeric_limits<int>::max()) throw StorageError("stored rule integer is out of range"); return static_cast<int>(value); }
std::string encode(const std::vector<Bracket>& brackets, const std::vector<Installment>& installments) { std::ostringstream output; for (const auto& item : brackets) output << item.lower_bound_cents << ',' << (item.upper_bound_cents ? std::to_string(*item.upper_bound_cents) : "N") << ',' << item.rate_ppm << ';'; output << '|'; if (installments.empty()) output << '-'; for (const auto& item : installments) output << item.quarter << ',' << item.due_date << ',' << item.period_ppm << ',' << item.cumulative_ppm << ';'; return output.str(); }
void decode(const std::string& text, std::vector<Bracket>& brackets, std::vector<Installment>& installments) { const auto sections=split(text,'|'); if(sections.size()!=2) throw StorageError("invalid stored rule payload"); for(const auto& entry:split(sections[0],';')) { const auto fields=split(entry,','); if(fields.size()!=3) throw StorageError("invalid bracket payload"); brackets.push_back({number(fields[0]), fields[1]=="N" ? std::nullopt : std::optional<Cents>{number(fields[1])}, integer(fields[2])}); } if(sections[1]=="-") return; for(const auto& entry:split(sections[1],';')) { const auto fields=split(entry,','); if(fields.size()!=4) throw StorageError("invalid installment payload"); installments.push_back({integer(fields[0]),fields[1],integer(fields[2]),integer(fields[3])}); } }
std::string sources_encode(const std::vector<Source>& sources) { std::ostringstream output; for(const auto& source:sources) output<<source.agency<<'\t'<<source.title<<'\t'<<source.url<<'\t'<<source.publication_date<<'\t'<<source.verification_date<<'\t'<<source.interpretation_note<<'\n'; return output.str(); }
std::vector<Source> sources_decode(const std::string& text) { std::vector<Source> sources; for(const auto& line:split(text,'\n')) { const auto fields=split(line,'\t'); if(fields.size()!=6) throw StorageError("invalid source payload"); sources.push_back({fields[0],fields[1],fields[2],fields[3],fields[4],fields[5]}); } return sources; }
std::string federal_payload(const FederalRules& rules) { return std::to_string(rules.standard_deduction_cents)+"/"+std::to_string(rules.age_or_blind_addition_cents)+"/"+std::to_string(rules.capital_loss_limit_cents)+"/"+std::to_string(rules.niit_threshold_cents)+"/"+std::to_string(rules.niit_rate_ppm)+"/"+std::to_string(rules.additional_medicare_threshold_cents)+"/"+std::to_string(rules.additional_medicare_rate_ppm)+"/"+encode(rules.ordinary_brackets,rules.installments)+"/"+encode(rules.preferential_brackets,{}); }
std::string california_payload(const CaliforniaRules& rules) { return std::to_string(rules.standard_deduction_cents)+"/"+std::to_string(rules.joint_personal_exemption_credit_cents)+"/"+std::to_string(rules.capital_loss_limit_cents)+"/"+std::to_string(rules.behavioral_health_services_threshold_cents)+"/"+std::to_string(rules.behavioral_health_services_rate_ppm)+"/"+encode(rules.ordinary_brackets,rules.installments); }
FederalRules federal_decode(const std::string& payload) { const auto values=split(payload,'/'); if(values.size()!=9)throw StorageError("invalid federal payload"); FederalRules rules; rules.standard_deduction_cents=number(values[0]);rules.age_or_blind_addition_cents=number(values[1]);rules.capital_loss_limit_cents=number(values[2]);rules.niit_threshold_cents=number(values[3]);rules.niit_rate_ppm=integer(values[4]);rules.additional_medicare_threshold_cents=number(values[5]);rules.additional_medicare_rate_ppm=integer(values[6]);decode(values[7],rules.ordinary_brackets,rules.installments);std::vector<Installment> ignored;decode(values[8],rules.preferential_brackets,ignored);return rules; }
CaliforniaRules california_decode(const std::string& payload) { const auto values=split(payload,'/');if(values.size()!=6)throw StorageError("invalid California payload");CaliforniaRules rules;rules.standard_deduction_cents=number(values[0]);rules.joint_personal_exemption_credit_cents=number(values[1]);rules.capital_loss_limit_cents=number(values[2]);rules.behavioral_health_services_threshold_cents=number(values[3]);rules.behavioral_health_services_rate_ppm=integer(values[4]);decode(values[5],rules.ordinary_brackets,rules.installments);return rules; }
std::vector<Installment> federal_installments(){return {{1,"2026-04-15",250000,250000},{2,"2026-06-15",250000,500000},{3,"2026-09-15",250000,750000},{4,"2027-01-15",250000,1000000}};} std::vector<Installment> california_installments(){return {{1,"2026-04-15",300000,300000},{2,"2026-06-15",400000,700000},{3,"2026-09-15",0,700000},{4,"2027-01-15",300000,1000000}};}
RuleRevision read_revision(sqlite3* database, std::int64_t id) { sqlite::Statement statement(database,"SELECT jurisdiction,official_baseline,modified,payload,sources FROM rule_revisions WHERE id=?");statement.bind_integer(1,id);if(!statement.step_row())throw StorageError("rule revision not found");RuleRevision result;result.id=id;result.jurisdiction=jurisdiction_from(statement.required_text(0,"rule jurisdiction"));result.official_baseline=statement.integer(1)!=0;result.modified=statement.integer(2)!=0;result.sources=sources_decode(statement.required_text(4,"rule sources"));const auto payload=statement.required_text(3,"rule payload");if(result.jurisdiction==Jurisdiction::federal){result.federal=federal_decode(payload);validate(*result.federal);}else{result.california=california_decode(payload);validate(*result.california);}return result; }
std::int64_t insert_revision(sqlite3* database,Jurisdiction jurisdiction,const std::string& payload,const std::vector<Source>& sources,bool modified) { sqlite::Statement order(database,"SELECT COALESCE(MAX(created_order),0)+1 FROM rule_revisions");if(!order.step_row())throw StorageError("read revision order failed");sqlite::Statement statement(database,"INSERT INTO rule_revisions(jurisdiction,official_baseline,modified,payload,sources,created_order) VALUES(?,0,?,?,?,?)");statement.bind_text(1,jurisdiction_name(jurisdiction));statement.bind_integer(2,modified);statement.bind_text(3,payload);statement.bind_text(4,sources_encode(sources));statement.bind_integer(5,order.integer(0));statement.step_done("insert rule revision");return sqlite3_last_insert_rowid(database); }
void move_active(sqlite3* database,Jurisdiction jurisdiction,std::int64_t id) { sqlite::Statement statement(database,"UPDATE active_rule_revisions SET revision_id=? WHERE jurisdiction=?");statement.bind_integer(1,id);statement.bind_text(2,jurisdiction_name(jurisdiction));statement.step_done("move active rule"); }
}  // namespace

void validate(const FederalRules& rules){if(rules.tax_year!=2026)throw RuleValidationError("federal tax year must be 2026");for(const auto value:{rules.standard_deduction_cents,rules.age_or_blind_addition_cents,rules.capital_loss_limit_cents,rules.niit_threshold_cents,rules.additional_medicare_threshold_cents})nonnegative(value);if(rules.niit_rate_ppm<0||rules.niit_rate_ppm>1'000'000||rules.additional_medicare_rate_ppm<0||rules.additional_medicare_rate_ppm>1'000'000)throw RuleValidationError("invalid federal rate");validate_brackets(rules.ordinary_brackets);validate_brackets(rules.preferential_brackets);validate_installments(rules.installments);} void validate(const CaliforniaRules& rules){if(rules.tax_year!=2026)throw RuleValidationError("California tax year must be 2026");for(const auto value:{rules.standard_deduction_cents,rules.joint_personal_exemption_credit_cents,rules.capital_loss_limit_cents,rules.behavioral_health_services_threshold_cents})nonnegative(value);if(rules.behavioral_health_services_rate_ppm<0||rules.behavioral_health_services_rate_ppm>1'000'000)throw RuleValidationError("invalid California rate");validate_brackets(rules.ordinary_brackets);validate_installments(rules.installments);}
FederalRules official_federal_rules(){return {2026,3220000,165000,{{0,2480000,100000},{2480000,10080000,120000},{10080000,21140000,220000},{21140000,40355000,240000},{40355000,51245000,320000},{51245000,76870000,350000},{76870000,std::nullopt,370000}},{{0,9890000,0},{9890000,61370000,150000},{61370000,std::nullopt,200000}},300000,25000000,38000,25000000,9000,federal_installments()};} CaliforniaRules official_california_rules(){return {2026,1141200,{{0,2215800,10000},{2215800,5252800,20000},{5252800,8290400,40000},{8290400,11508400,60000},{11508400,14544800,80000},{14544800,74295800,93000},{74295800,89154200,103000},{89154200,148590600,113000},{148590600,std::nullopt,123000}},30600,300000,100000000,10000,california_installments()};}
std::vector<Source> official_federal_sources(){return {{"IRS","2026 Form 1040-ES","https://www.irs.gov/pub/irs-pdf/f1040es.pdf","2026","2026-04-01","Standard deduction, Schedule Y-1, and payment dates."},{"IRS","Publication 505 (2026)","https://www.irs.gov/publications/p505","2026","2026-04-01","Preferential schedule, loss limit, and additional taxes."},{"IRS","Topic no. 559","https://www.irs.gov/taxtopics/tc559","not stated","2026-04-01","NIIT threshold and rate."},{"IRS","Topic no. 560","https://www.irs.gov/taxtopics/tc560","2019-06-04","2026-04-01","Additional Medicare threshold and rate."}};} std::vector<Source> official_california_sources(){return {{"California FTB","2026 Form 540-ES instructions","https://www.ftb.ca.gov/forms/2026/2026-540-es-instructions.html","2026","2026-04-01","Standard deduction, installments, and Behavioral Health Services Tax."},{"California FTB","2025 Form 540 instructions","https://www.ftb.ca.gov/forms/2025/2025-540-booklet.html","2025","2026-04-01","Schedule Y, used as directed by the 2026 worksheet."},{"California FTB","2025 Form 540 2EZ booklet","https://www.ftb.ca.gov/forms/2025/2025-540-2ez-booklet.html","2025","2026-04-01","$306 joint credit derived from two published $153 personal exemptions."},{"California FTB","2025 Schedule D (540) instructions","https://www.ftb.ca.gov/forms/2025/2025-540-d-instructions.html","2025","2026-04-01","$3,000 capital-loss limit for MFJ."}};}
struct RuleStore::Connection { explicit Connection(const std::string& path):sqlite(path){} sqlite::Connection sqlite;};
RuleStore::RuleStore(const std::string& path):connection_(std::make_unique<Connection>(path)){InputStore bootstrap(path);auto& db=connection_->sqlite;sqlite::Transaction tx(db);sqlite::Statement version(db.get(),"SELECT MAX(version) FROM schema_migrations");if(!version.step_row())throw StorageError("read schema version failed");if(version.integer(0)>kRuleSchemaVersion)throw StorageError("database schema is newer than this application");if(version.integer(0)<2){db.execute("CREATE TABLE rule_revisions (id INTEGER PRIMARY KEY, jurisdiction TEXT NOT NULL CHECK(jurisdiction IN ('federal','california')), official_baseline INTEGER NOT NULL CHECK(official_baseline IN(0,1)), modified INTEGER NOT NULL CHECK(modified IN(0,1)), payload TEXT NOT NULL, sources TEXT NOT NULL, created_order INTEGER NOT NULL UNIQUE, CHECK(official_baseline=0 OR modified=0)); CREATE TABLE active_rule_revisions (jurisdiction TEXT PRIMARY KEY CHECK(jurisdiction IN ('federal','california')), revision_id INTEGER NOT NULL REFERENCES rule_revisions(id)); CREATE TRIGGER prevent_official_rule_update BEFORE UPDATE ON rule_revisions WHEN OLD.official_baseline = 1 BEGIN SELECT RAISE(ABORT, 'official baselines are immutable'); END; CREATE TRIGGER prevent_official_rule_delete BEFORE DELETE ON rule_revisions WHEN OLD.official_baseline = 1 BEGIN SELECT RAISE(ABORT, 'official baselines are immutable'); END;");auto seed=[&](Jurisdiction j,const std::string& p,const std::vector<Source>& s,std::int64_t order){sqlite::Statement statement(db.get(),"INSERT INTO rule_revisions(jurisdiction,official_baseline,modified,payload,sources,created_order) VALUES(?,1,0,?,?,?)");statement.bind_text(1,jurisdiction_name(j));statement.bind_text(2,p);statement.bind_text(3,sources_encode(s));statement.bind_integer(4,order);statement.step_done("seed rules");return sqlite3_last_insert_rowid(db.get());};const auto f=seed(Jurisdiction::federal,federal_payload(official_federal_rules()),official_federal_sources(),1);const auto c=seed(Jurisdiction::california,california_payload(official_california_rules()),official_california_sources(),2);for(const auto [j,id]:{std::pair{Jurisdiction::federal,f},std::pair{Jurisdiction::california,c}}){sqlite::Statement statement(db.get(),"INSERT INTO active_rule_revisions VALUES(?,?)");statement.bind_text(1,jurisdiction_name(j));statement.bind_integer(2,id);statement.step_done("seed active rules");}db.execute("INSERT INTO schema_migrations VALUES(2)");}tx.commit();}
RuleStore::~RuleStore()=default;
ActiveRules RuleStore::load_active()const{std::optional<std::int64_t> federal,california;sqlite::Statement statement(connection_->sqlite.get(),"SELECT jurisdiction,revision_id FROM active_rule_revisions");while(statement.step_row()){if(jurisdiction_from(statement.required_text(0,"active rule jurisdiction"))==Jurisdiction::federal)federal=statement.integer(1);else california=statement.integer(1);}if(!federal||!california)throw StorageError("active rules are incomplete");auto f=read_revision(connection_->sqlite.get(),*federal);auto c=read_revision(connection_->sqlite.get(),*california);const bool federal_customized=f.federal != official_federal_rules();const bool california_customized=c.california != official_california_rules();return {std::move(f),std::move(c),federal_customized,california_customized};}
void RuleStore::replace_active(const FederalRules& f,const CaliforniaRules& c){validate(f);validate(c);sqlite::Transaction tx(connection_->sqlite);const auto federal=insert_revision(connection_->sqlite.get(),Jurisdiction::federal,federal_payload(f),official_federal_sources(),f!=official_federal_rules());const auto california=insert_revision(connection_->sqlite.get(),Jurisdiction::california,california_payload(c),official_california_sources(),c!=official_california_rules());move_active(connection_->sqlite.get(),Jurisdiction::federal,federal);move_active(connection_->sqlite.get(),Jurisdiction::california,california);tx.commit();}
void RuleStore::restore_official(Jurisdiction jurisdiction){sqlite::Transaction transaction(connection_->sqlite);const auto id=jurisdiction==Jurisdiction::federal?insert_revision(connection_->sqlite.get(),jurisdiction,federal_payload(official_federal_rules()),official_federal_sources(),false):insert_revision(connection_->sqlite.get(),jurisdiction,california_payload(official_california_rules()),official_california_sources(),false);move_active(connection_->sqlite.get(),jurisdiction,id);transaction.commit();}
void RuleStore::restore_archived(Jurisdiction jurisdiction,std::int64_t id){const auto source=read_revision(connection_->sqlite.get(),id);if(source.jurisdiction!=jurisdiction||source.official_baseline)throw RuleValidationError("revision cannot be restored for this jurisdiction");sqlite::Transaction transaction(connection_->sqlite);const auto replacement=source.federal?insert_revision(connection_->sqlite.get(),jurisdiction,federal_payload(*source.federal),source.sources,source.modified):insert_revision(connection_->sqlite.get(),jurisdiction,california_payload(*source.california),source.sources,source.modified);move_active(connection_->sqlite.get(),jurisdiction,replacement);transaction.commit();}
std::vector<RuleRevision> RuleStore::archived_revisions(Jurisdiction j)const{const auto active=load_active();const auto active_id=j==Jurisdiction::federal?active.federal.id:active.california.id;sqlite::Statement statement(connection_->sqlite.get(),"SELECT id FROM rule_revisions WHERE jurisdiction=? AND official_baseline=0 AND id<>? ORDER BY created_order");statement.bind_text(1,jurisdiction_name(j));statement.bind_integer(2,active_id);std::vector<RuleRevision> revisions;while(statement.step_row())revisions.push_back(read_revision(connection_->sqlite.get(),statement.integer(0)));return revisions;}
} // namespace estimated_taxes
